version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=hhplus
    volumes:
      - ./data/mysql/:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    restart: always
    # 비밀번호 필요시 주석 해제
    # environment:
    #   - REDIS_PASSWORD=yourpassword
    # command: ["redis-server", "--requirepass", "yourpassword"]
    volumes:
      - ./data/redis-data/:/data

networks:
  default:
    driver: bridge