@startuml

hide footbox
autoactivate on

participant "Service Client" as sc
participant "Product Controller" as pc
participant "Product Service" as ps
participant "Product Repository" as pr

group Step 1. 상품 조회 요청
    autonumber 1 "(0)"
    sc -> pc : GET /products/{productId}
    pc -> ps : getProduct(productId)
end

group Step 2. 상품 조회
    ps -> pr : getProduct(productId)
    pr --> ps : product: Product
end

group Step 3. 응답 반환
    ps -> ps : map to productResponseDto
    ps --> pc : productResponseDto
    pc --> sc : HTTP 200 OK, productResponseDto
end

@enduml