@startgantt

-- 2주차 --
Project starts 2025-05-23
' 2주차 주요 마일스톤
[서버 구축 설계] starts 2025-05-23 and ends 2025-05-29
[시퀀스 다이어그램 작성 완료] happens 2025-05-29
[ERD 작성 완료] happens 2025-05-29
[클래스 다이어그램 작성 완료] happens 2025-05-29
[인프라 구성도 작성 완료] happens 2025-05-29
[마일스톤 정리 완료] happens 2025-05-29
[기능/비기능 요구사항 정리 완료] happens 2025-05-29

-- 3주차 --
' 3주차 주요 마일스톤
[도메인 모델링 및 계층 구조 설계] starts 2025-05-30 and ends 2025-06-05

-- 4주차 --
' 4주차 주요 마일스톤
[비즈니스 요구사항] starts 2025-06-06 and ends 2025-06-12

-- 5주차 --
' 5주차 주요 마일스톤
[동시성 문제 분석 및 제어] starts 2025-06-13 and ends 2025-06-19

-- 6주차 --
' 6주차 주요 마일스톤
[분산락 & 캐싱 전략 설계] starts 2025-06-20 and ends 2025-06-26

-- 7주차 --
' 7주차 주요 마일스톤
[Redis기반 랭킹 시스템 및 비동기 시스템 설계] starts 2025-06-27 and ends 2025-07-03


-- 8주차 --
' 8주차 주요 마일스톤
[트랜잭션 범위 분석 & 트랜잭션 분리 및 이벤트 기반 비즈니스 분할] starts 2025-07-04 and ends 2025-07-10


-- 9주차 --
' 9주차 주요 마일스톤
[Kafka 구성] starts 2025-07-11 and ends 2025-07-17

-- 10주차 --
' 10주차 주요 마일스톤
[서버 부하 테스트 & 장애 시나리오 작성 및 복구 사이클 경험] starts 2025-07-18 and ends 2025-07-24

@endgantt
